In [3]:
import numpy as np

In [4]:
ridership = np.array([
    [   0,    0,    2,    5,    0],
    [1478, 3877, 3674, 2328, 2539],
    [1613, 4088, 3991, 6461, 2691],
    [1560, 3392, 3826, 4787, 2613],
    [1608, 4802, 3932, 4477, 2705],
    [1576, 3933, 3909, 4979, 2685],
    [  95,  229,  255,  496,  201],
    [   2,    0,    1,   27,    0],
    [1438, 3785, 3589, 4174, 2215],
    [1342, 4043, 4009, 4665, 3033]
])

In [5]:
ridership

array([[   0,    0,    2,    5,    0],
       [1478, 3877, 3674, 2328, 2539],
       [1613, 4088, 3991, 6461, 2691],
       [1560, 3392, 3826, 4787, 2613],
       [1608, 4802, 3932, 4477, 2705],
       [1576, 3933, 3909, 4979, 2685],
       [  95,  229,  255,  496,  201],
       [   2,    0,    1,   27,    0],
       [1438, 3785, 3589, 4174, 2215],
       [1342, 4043, 4009, 4665, 3033]])

In [28]:
ridership[0]

array([0, 0, 2, 5, 0])

In [32]:
ridership[0, 3]

5

In [40]:
ridership[3:6, :3]

array([[1560, 3392, 3826],
       [1608, 4802, 3932],
       [1576, 3933, 3909]])

In [43]:
ridership[:3]

array([[   0,    0,    2,    5,    0],
       [1478, 3877, 3674, 2328, 2539],
       [1613, 4088, 3991, 6461, 2691]])

In [47]:
ridership[0, :] + ridership[1,]

array([1478, 3877, 3676, 2333, 2539])

In [48]:
ridership[0, :] + ridership[1:]

array([[1478, 3877, 3676, 2333, 2539],
       [1613, 4088, 3993, 6466, 2691],
       [1560, 3392, 3828, 4792, 2613],
       [1608, 4802, 3934, 4482, 2705],
       [1576, 3933, 3911, 4984, 2685],
       [  95,  229,  257,  501,  201],
       [   2,    0,    3,   32,    0],
       [1438, 3785, 3591, 4179, 2215],
       [1342, 4043, 4011, 4670, 3033]])

In [50]:
a = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
b = np.array([[1, 1, 1], [2, 2, 2], [3, 3, 3]])

In [51]:
a + b

array([[ 2,  3,  4],
       [ 6,  7,  8],
       [10, 11, 12]])

In [61]:
'''
    Find the station with the maximum riders on the
    first day, then return the mean riders per day for that station. Also
    return the mean ridership overall for comparsion.
    
    Hint: NumPy's argmax() function might be useful:
    http://docs.scipy.org/doc/numpy/reference/generated/numpy.argmax.html
'''

np.argmax(ridership[0])

3

In [58]:
ridership[:, 3].mean(), ridership.mean()

(3239.9, 2342.6)

In [59]:
a = np.array([
        [1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]
    ])
    
a.sum(), a.sum(axis=0), a.sum(axis=1)

(45, array([12, 15, 18]), array([ 6, 15, 24]))

In [62]:
'''
    Fill in this function. First, for each subway station, calculate the
    mean ridership per day. Then, out of all the subway stations, return the
    maximum and minimum of these values. That is, find the maximum
    mean-ridership-per-day and the minimum mean-ridership-per-day for any
    subway station.
'''

ridership.mean(axis=0)

array([1071.2, 2814.9, 2718.8, 3239.9, 1868.2])

In [63]:
ridership.mean(axis=0).min()

1071.2

In [64]:
ridership.mean(axis=0).max()

3239.9

In [65]:
ridership.mean(axis=1)

array([1.4000e+00, 2.7792e+03, 3.7688e+03, 3.2356e+03, 3.5048e+03,
       3.4164e+03, 2.5520e+02, 6.0000e+00, 3.0402e+03, 3.4184e+03])