In [1]:
import numpy as np

In [2]:
countries = np.array([
    'Afghanistan', 'Albania', 'Algeria', 'Angola', 'Argentina',
    'Armenia', 'Australia', 'Austria', 'Azerbaijan', 'Bahamas',
    'Bahrain', 'Bangladesh', 'Barbados', 'Belarus', 'Belgium',
    'Belize', 'Benin', 'Bhutan', 'Bolivia',
    'Bosnia and Herzegovina'
])

In [16]:
employment = np.array([
    55.70000076,  51.40000153,  50.5       ,  75.69999695,
    58.40000153,  40.09999847,  61.5       ,  57.09999847,
    60.90000153,  66.59999847,  60.40000153,  68.09999847,
    66.90000153,  53.40000153,  48.59999847,  56.79999924,
    71.59999847,  58.40000153,  70.40000153,  41.20000076
])

In [5]:
countries[0:3]

array(['Afghanistan', 'Albania', 'Algeria'], dtype='<U22')

In [6]:
countries[:3]

array(['Afghanistan', 'Albania', 'Algeria'], dtype='<U22')

In [7]:
countries[17:]

array(['Bhutan', 'Bolivia', 'Bosnia and Herzegovina'], dtype='<U22')

In [10]:
countries.dtype

dtype('<U22')

In [17]:
employment.dtype

dtype('float64')

In [18]:
np.array([0, 1, 2, 3]).dtype

dtype('int64')

In [19]:
np.array([1.0, 1.5, 2.0, 2.5]).dtype

dtype('float64')

In [20]:
np.array([True, False, False]).dtype

dtype('bool')

In [26]:
np.array(['Sushi', 'Afterlife']).dtype

dtype('<U9')

In [27]:
np.array(['AL', 'AK', 'AZ', 'AR', 'CA']).dtype

dtype('<U2')

In [31]:
range(len(countries))

range(0, 20)

In [35]:
for i in range(len(countries)):
    print("{} has employement rate of {:.2f}%".format(countries[i], employment[i]))

Afghanistan has employement rate of 55.70%
Albania has employement rate of 51.40%
Algeria has employement rate of 50.50%
Angola has employement rate of 75.70%
Argentina has employement rate of 58.40%
Armenia has employement rate of 40.10%
Australia has employement rate of 61.50%
Austria has employement rate of 57.10%
Azerbaijan has employement rate of 60.90%
Bahamas has employement rate of 66.60%
Bahrain has employement rate of 60.40%
Bangladesh has employement rate of 68.10%
Barbados has employement rate of 66.90%
Belarus has employement rate of 53.40%
Belgium has employement rate of 48.60%
Belize has employement rate of 56.80%
Benin has employement rate of 71.60%
Bhutan has employement rate of 58.40%
Bolivia has employement rate of 70.40%
Bosnia and Herzegovina has employement rate of 41.20%


In [36]:
employment.mean()

58.68500003850001

In [37]:
employment.std()

9.338269113687888

In [38]:
employment.max()

75.69999695

In [39]:
employment.sum()

1173.70000077

In [48]:
np.where(employment == employment.max())

(array([3]),)

In [51]:
country = countries[np.where(employment == employment.max())]
country

array(['Angola'], dtype='<U22')

In [52]:
countries[np.where(employment < 50.0)]

array(['Armenia', 'Belgium', 'Bosnia and Herzegovina'], dtype='<U22')

## Vector Operations

In [66]:
a = np.array([1,3,5])
b = np.array([2,4,6])

In [86]:
a / 2

array([0.5, 1.5, 2.5])

In [87]:
b ** 2

array([ 4, 16, 36])

In [88]:
a > b

array([False, False, False])

In [95]:
a > 4

array([False, False,  True])

In [89]:
x = np.array([True, False, True])
y = np.array([False, True, True])

In [90]:
x & y

array([False, False,  True])

In [91]:
x & True

array([ True, False,  True])

In [92]:
~x

array([False,  True, False])

In [93]:
x > y

array([ True, False, False])

In [94]:
x == y

array([False, False,  True])

In [97]:
female_completion = np.array([
    97.35583,  104.62379,  103.02998,   95.14321,  103.69019,
    98.49185,  100.88828,   95.43974,   92.11484,   91.54804,
    95.98029,   98.22902,   96.12179,  119.28105,   97.84627,
    29.07386,   38.41644,   90.70509,   51.7478 ,   95.45072
])

male_completion = np.array([
     95.47622,  100.66476,   99.7926 ,   91.48936,  103.22096,
     97.80458,  103.81398,   88.11736,   93.55611,   87.76347,
    102.45714,   98.73953,   92.22388,  115.3892 ,   98.70502,
     37.00692,   45.39401,   91.22084,   62.42028,   90.66958
])

In [101]:
overall_completion = (female_completion + male_completion) / 2
overall_completion

array([ 96.416025, 102.644275, 101.41129 ,  93.316285, 103.455575,
        98.148215, 102.35113 ,  91.77855 ,  92.835475,  89.655755,
        99.218715,  98.484275,  94.172835, 117.335125,  98.275645,
        33.04039 ,  41.905225,  90.962965,  57.08404 ,  93.06015 ])